// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAdnW-cggnS9lkqIHtdJJJGJsdWkCsS5bg',
    appId: '1:100129363441:web:a90e2592b81052fc8a2050',
    messagingSenderId: '100129363441',
    projectId: 'billingsoftware-88613',
    authDomain: 'billingsoftware-88613.firebaseapp.com',
    storageBucket: 'billingsoftware-88613.firebasestorage.app',
    measurementId: 'G-SGE5ZGL719',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCC3P4xq_B08KFLI8d14X_7a7H6HKWnbFU',
    appId: '1:100129363441:android:72f6c28dc0be84ac8a2050',
    messagingSenderId: '100129363441',
    projectId: 'billingsoftware-88613',
    storageBucket: 'billingsoftware-88613.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBUcLK0zN8iBMOjcCLwnJnjpVYTwd_ViSc',
    appId: '1:100129363441:ios:5e31fd7931a090f58a2050',
    messagingSenderId: '100129363441',
    projectId: 'billingsoftware-88613',
    storageBucket: 'billingsoftware-88613.firebasestorage.app',
    iosBundleId: 'com.example.kiosSystem',
  );
}
